default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: blue_development

test:
  <<: *default
  database: blue_test

production:
  <<: *default
  database: blue_production
  username: blue
  password: <%= ENV['BLUE_DATABASE_PASSWORD'] %>
